{% set name = "padelpy" %}
{% set version = "0.1.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/padelpy-{{ version }}.tar.gz
  sha256: 9fc4f73b009b2d988b6f2a2a226e879a09a9b788343c3ac773dd7ddf3fef73d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - openjdk

test:
  imports:
    - padelpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecrl/padelpy
  summary: A Python wrapper for PaDEL-Descriptor
  license: AGPL-3.0-only AND LGPL-2.1-only AND MIT
  license_file:
    - padelpy/PaDEL-Descriptor/license/LICENSE.txt
    - padelpy/PaDEL-Descriptor/license/lgpl-2.1.txt
    - padelpy/PaDEL-Descriptor/license/lgpl.license
    - LICENSE
extra:
  recipe-maintainers:
    - maclandrol
